### ISSUE TITLE
'Testing' section example code

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/devise_pundit_readme#1]
Under the 'Testing' section, there is some sample code that reads:

```
    class PostPolicyTest
      test "users can't update others posts" do
        amethyst = users(:amethyst)
        post = posts(:garnet_private)
        expect(post.user).not_to eq(methyst)
        expect(PostPolicy.new(amethyst, post).update?).to be false
      end
    end
```

It would make sense if online 5, instead of `expect(post.user).not_to eq(methyst)` it read `expect(post.user).not_to eq(amethyst)`. The user 'methyst' doesn't exist, but user 'amethyst' does exist, and is not the creator of the post.

I'm not sure if this edit right, but students could be confused, thinking that the 'amethyst' IS actually the posts user. If this edit is right, I can edit the lesson to save you guys some time ^^

**Comment by pletcher** [comment]
Thanks for reporting this! Fixed in https://github.com/learn-co-curriculum/devise_pundit_readme/commit/a919dbd9f06035f7097b992f8e47d19ed2c048e0
